version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: user1
      POSTGRES_DB: stocks_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
